### ISSUE TITLE
Contributing.md is empty and needs updation

### ISSUE THREAD

**Issue by gayatribelapurkar** [Auto-DL/Auto-DL#128]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?
No

### Feature Description

contributing.md file needs to be updated as it is empty.

**Comment by ADI10HERO** [comment]
@Rahul524 Can Prathmesh or someone help us with this?

**Comment by bamblebam** [comment]
@ADI10HERO I think this issue should be closed since now we have a contributing.md file
