### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by rajraj889** [Auto-DL/Auto-DL#156]
### Current Behavior

The README is outdated.

### Expected behavior/code

Remove all unnecessary lines and update it with current scenario. 

### ⚙️ Environment

- `Python` version(s):
    - *good*: [e.g. 3.8]
    - **better**: [3.8.6 - Clang 12.0.0 (clang-1200.0.32.27)]
- `OS`: [e.g. Ubuntu 18.04, OSX 10.13.4, Windows 10]

**Comment by chicken-biryani** [comment]
Can you assign this to me?
