### ISSUE TITLE
Dynamic name for downloaded file

### ISSUE THREAD

**Issue by shintan777** [Auto-DL/Auto-DL#158]
### Current Behavior
Currently, the name is always test.py for the downloaded file

### Expected behavior/code
It should be saved as per the name provided in the project details

### ⚙️ Environment

- `Python` version(s): 3.7.9
- `OS`: Windows 10

**Comment by rajraj889** [comment]
Check download_code fn in Step2.js, make the string dynamic by fetching the output file name from localstorage . Also check for edge cases.
