### ISSUE TITLE
Refactoring the README

### ISSUE THREAD

**Issue by chicken-biryani** [Auto-DL/Auto-DL#168]
Since, a readme is the first document a visitor looks at it should be proper, precise and should give away as much as information possible.

**Comment by chicken-biryani** [comment]
@ADI10HERO Could you please assign this issue to me?

**Comment by ADI10HERO** [comment]
See #156

**Comment by ADI10HERO** [comment]
I will assign you #156 too, feel free to make PR that closes both these issues (#156, #168)

**Comment by ADI10HERO** [comment]
@chicken-biryani Can you please comment on that issue as well?
