### ISSUE TITLE
In home , onhover on a table row should change color & onclick it should redirect to project page

### ISSUE THREAD

**Issue by rajraj889** [Auto-DL/Auto-DL#172]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### Feature Description

Remove the arrow icon and add the onclick redirecting functionality.
![image](https://user-images.githubusercontent.com/40288700/122579746-dac31800-d072-11eb-9c60-39817324d620.png)

**Comment by ADI10HERO** [comment]
Fixed by #194
