### ISSUE TITLE
Add another field on new project ie Project Description

### ISSUE THREAD

**Issue by rajraj889** [Auto-DL/Auto-DL#185]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### Feature Description

Add another field (Project description) below Project name, work on both backend and frontend.

![image](https://user-images.githubusercontent.com/40288700/123262442-822dc800-d515-11eb-9a22-5baf932357f8.png)

**Comment by ADI10HERO** [comment]
Fixed by #194
