### ISSUE TITLE
Update PR template to make it more inclusive

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Auto-DL#204]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description
The current PR template is Backend oriented. Need of a PR template that is more inclusive of more than one kind of contribution Is needed. (Docs/DevOps/Backend/Frontend)

### Possible Solution

Make it domain agnostic and try to keep it general? 
Or create cases for example `format your code using Black/Prettier/Xyz...`

**Comment by bamblebam** [comment]
I will do this
