### ISSUE TITLE
Tensorflow update to 2.5.0

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Auto-DL#214]
### Current Behavior

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.2 (from -r /tmp/build_3bae75f6/requirements.txt (line 5)) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.6.0rc0)
       ERROR: No matching distribution
```

### Expected behavior/code

pip install -r requirements.txt to complete without any errors

### ⚙️ Environment

- `Python` version(s):
    - *good*: 3.9
    - **better**: 3.9.6

### Possible Solution

Update in requirements.txt

**Comment by RusherRG** [comment]
5.2.0? Did you mean 2.5.0? @ADI10HERO

**Comment by ADI10HERO** [comment]
Woops! yes I did 😂
