### ISSUE TITLE
Persistence of Parameters in Step 2

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#217]
## Bug Report

Values entered in `step-2` do not get saved when the component unmounts.

### Current Behavior
The values entered in the different tabs of `step-2` (**Preprocessing Params**, **Model Layers**, and **Hyperparams**) are not saved unless clicked on any other tab (listed above). For example, after entering values in any tab if the user clicks on the Home icon, the values entered in the current tab are not persisted.

### Expected behavior/code
The entered values must be saved whenever the tab / component unmounts, rather than when another tab is clicked.

**Comment by rajraj889** [comment]
We can do the API calls in the return part as shown in the code below.

useEffect(() => {
  window.addEventListener('mousemove', () => {});

  // returned function will be called on component unmount 
  return () => {
    window.removeEventListener('mousemove', () => {})
  }
}, [])

**Comment by rushic24** [comment]
can anyone assign this to me

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue @McTechie

**Comment by McTechie** [comment]
Sure, go right ahead! Kindly note this Issue pertains to Version 1 (React) Frontend of the repo.
It would be great if you could update us regularly on the status of your work. Furthermore, if you do have any doubts feel free to ask them here or via Slack! xD

**Comment by ShwetKhatri2001** [comment]
Can you please confirm are we still facing this issue ? 
According to me as we are setting the project_data to localstorage on selecting project and getting it  on tabs, we should not have any problem on any tab change or refresh ( demo given below for ref). 
Also its saving every update on projects correctly.

Let me know if this issue or any similar issue is still there.


https://user-images.githubusercontent.com/56475750/151679392-23abcb4c-b2eb-4814-9f72-25376893db16.mp4

**Comment by McTechie** [comment]
@ShwetKhatri2001 Yes, we still are facing this issue.
The crux being that the data persists only when a Tab is changed... Upon directly navigating to a different page or refreshing the current one, the Parameters do not persist correctly (the loss being more on addition of more parameters).

For more info, you can refer the video below:

https://user-images.githubusercontent.com/69250084/151918724-897f680d-5e1c-4cdb-ac54-48830ce469be.mp4
