### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by bamblebam** [Auto-DL/Auto-DL#258]
## Bug Report
There are a lot of dead links in readme:
1. DLMML API
2. Dev Guidelines
3. User Guidelines

Either remove them or replace them.
This is probably related to #156 

### Current Behavior

Links just go to the standard github 404 page
### Expected behavior/code

Should have a working link

### ⚙️ Environment

- `Python` version(s):
    - *good*: [e.g. 3.8]
    - **better**: [3.8.6 - Clang 12.0.0 (clang-1200.0.32.27)]
- `OS`: [e.g. Ubuntu 18.04, OSX 10.13.4, Windows 10]

**Comment by bugs-sunny** [comment]
Can I take this issue for hacktoberfest?

**Comment by bamblebam** [comment]
The ReadMe Refactor is already going on, so no. You can check the other issues if you find something

**Comment by bugs-sunny** [comment]
coolio
