### ISSUE TITLE
Clear Warnings on Frontend Console

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#293]
## Bug Report

The `FrontEndApp` has warnings / errors which appear onto the console when run (`npm start`). This causes a few warnings to appear during testing the Frontend using React Testing Library. Additionally, hosting the frontend on platforms such as Netlify and Vercel would be unsuccessful due to the warnings.

### Current Behavior

Multiple warnings / errors due to improper state handling, unused variables, etc. is shown onto the console while running the `FrontEndApp`.

### Expected Behavior

Efficiently cleanup the code so that no errors / warnings should be shown onto the console when running, testing or even deploying the frontend application.

### ⚙️ Environment

- `Python` version(s): 3.9.6
- `OS`: Windows 10

### Screenshots

Some of the warnings / errors have been shown below.

<img width="527" alt="1" src="https://user-images.githubusercontent.com/69250084/129133651-b757ec57-0a6b-4430-8034-802df779d6e4.png">
<img width="521" alt="2" src="https://user-images.githubusercontent.com/69250084/129133663-f1a57586-5e9e-486f-a1e2-267c76b51d16.png">

**Comment by gagandeepp** [comment]
is this assigned ??

**Comment by RusherRG** [comment]
Yeah there's already a PR made #353
Although it's a partial fix, have a look at the comments in the PR and if you could fix the remaining warnings it would be great.

**Comment by Christian-Oleson** [comment]
I'm working on this one, yeah. I'm not a react dev, so I got a bit stuck with a useEffect wrapper implementation to prevent multiple renders. I could use help with that.

**Comment by McTechie** [comment]
Fixed in #353 and #406
