### ISSUE TITLE
Email validation doesn't accept uppercase characters

### ISSUE THREAD

**Issue by RusherRG** [Auto-DL/Auto-DL#316]
### Current Behavior

The email validation in `BackEndApp/authv1/models.py` uses the following regex `^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$`
It doesn't allow upper case characters.

### Expected behavior/code

Should accept uppercase characters.

### ⚙️ Environment

- `Python` version(s): 3.8.5
- `OS`: Ubuntu 20.04

### Possible Solution

Update the regex to accept uppercase characters or else connect the email to lower case before validating using the regex. Using the latter would be better since email addresses should be case-sensitive.

**Comment by Akshansh99** [comment]
hey @RusherRG 
Can I work on this issue?

**Comment by ADI10HERO** [comment]
Sure @Akshansh99  Please go ahead

**Comment by mharyam** [comment]
Hell @RusherRG 
I have already worked on this 
I have created a pull request

**Comment by mharyam** [comment]
Hello @ADI10HERO 

I have created a pull request, kindly check it out 
https://github.com/Auto-DL/Auto-DL/pull/318
