### ISSUE TITLE
Purge Unwanted Imports in BackEndApp

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#320]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

Many files present in the `BackEndApp` consist of many unused / unwanted imports.

### Possible Solution

Remove the non-essential imports from the `BackEndApp`.
This will help the codebase remain clean and concise! 😄

**Comment by a-sambhab** [comment]
Hey, @McTechie can I work on this??
if yes, please assign it to me

**Comment by McTechie** [comment]
Yes @a-sambhab, you sure can! 😄

**Comment by a-sambhab** [comment]
@McTechie please review PR #378 for the above issue
