### ISSUE TITLE
Pre-existing users after login get stuck on an error page.

### ISSUE THREAD

**Issue by bamblebam** [Auto-DL/Auto-DL#321]
### Current Behavior

When a pre existing user who has one or more projects logs in he gets an error.  
![image](https://user-images.githubusercontent.com/53450613/132727454-984dc9d6-7e16-49e4-8e87-6c6cf6631b91.png)

The reason for this might be one of the following:
1. The models have been changed adding/removing some functionality like adding an additional field whose metadata the previously created projects do not have.
2. The default value of the project_description (variable named in react) is either null or undefined which does not have the property length. This gives an issue if the project doesn't have a description. The issue is probably in the below code statement.

https://github.com/Auto-DL/Auto-DL/blob/758b08f52f99348a13c7b84fef398d4ae5ed561b/FrontEndApp/v1-react/src/Components/MainApp/projects/ProjectTable.js#L383-L393

This issue is also extra dangerous since it happens after the user has successfully logged in and the creds have been stored in local storage so any attempt to reload or restart the server has no effect. One needs to go incognito and create a new user.   

I tested this by creating a new user and the error didn't show up, further confirming my hypothesis.

This should be fixed ASAP.

### Expected behavior/code

It should show all my projects.

### Possible Solution

There should probably be some check whether the project description exists or no, or the default value should be changed.  
This might not be so grave since most of the pre existing users are devs, but these practices could be harmful.

### Additional context/Screenshots

There may be similar issues in other parts of the code which haven't been detected yet. Should also find those.

**Comment by Harshit22Zest** [comment]
my name is harshit kalucha i want to take this issue

**Comment by bamblebam** [comment]
> my name is harshit kalucha i want to take this issue

The issue is that we are checking the length property of something that is undefined or null, in this case project.description, so just add a check for it.  

If you have any problems lemme know.  
:)

**Comment by ShwetKhatri2001** [comment]
@bamblebam I'd like to fix this issue

**Comment by RusherRG** [comment]
This issue is no longer an issue it has been fixed.
