### ISSUE TITLE
Preprocessing Parameter State does not persist on switching tabs.

### ISSUE THREAD

**Issue by bamblebam** [Auto-DL/Auto-DL#322]
### Current Behavior

When tabs are switched the parameters in the preprocessing tab do not persist. They probably aren't getting saved or something.

### Expected behavior/code

The parameters should persist.

**Comment by McTechie** [comment]
@bamblebam An issue for this has been created already xD

`Issue: #217`

**Comment by bamblebam** [comment]
Oh alright then will close this issue. :)
