### ISSUE TITLE
Add emojis to make the .md files cuter

### ISSUE THREAD

**Issue by bamblebam** [Auto-DL/Auto-DL#361]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### Feature Description

Add emojis to make the .md files cuter.  
Was browsing github and came across some wonderful .md files thought it would make ours better.

<!-- Optional Sections below. Remove if not being used --

**Comment by STM3900** [comment]
Asign me, i will do that

**Comment by bamblebam** [comment]
> Asign me, i will do that

It has already been done, you can look at the other issues
