### ISSUE TITLE
Create a Bug Report Issue Template for Next.js

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#370]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

An Issue Template specifically catered towards the newer V2 Frontend developed in Next.js.
The template must be for **reporting a new bug** in the previously existing codebase (`FrontEndApp/autodl-platform`).

### Possible Solution

Create a new `NextJS Bug.md` file in `.github/ISSUE_TEMPLATE` directory.

### Additional Context

Remember to add comments in the template so as to guide the user appropriately (when the template is used).

**Comment by Aniket762** [comment]
Hey @McTechie would love to do this! Can you please assign this to me?

**Comment by Aniket762** [comment]
Thanks a lot @bamblebam on it 😎

**Comment by ADI10HERO** [comment]
Closing this Issue as per discussion on slack. Thanks to all contributors. Requesting y'all to have a look at other open issues. 😄
