### ISSUE TITLE
Create a Feature Request Issue Template for Django

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#371]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

An Issue Template specifically catered towards the Backend of AutoDL (developed in Django).
The template must be for **requesting a new feature addition** to the previously existing codebase (`BackEndApp`).

### Possible Solution

Create a new `Django Feature.md` file in `.github/ISSUE_TEMPLATE` directory.

### Additional Context

Remember to add comments in the template so as to guide the user appropriately (when the template is used).

**Comment by askalik** [comment]
Could i take this one?

**Comment by bamblebam** [comment]
> Could i take this one?

I assigned this to you. If you have any doubts lemme know

**Comment by ADI10HERO** [comment]
Closing this Issue as per discussion on slack. Thanks to all contributors. Requesting y'all to have a look at other open issues. 😄
