### ISSUE TITLE
Create a Bug Report Issue Template for Django

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#372]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

An Issue Template specifically catered towards the Backend of AutoDL (developed in Django).
The template must be for **reporting a new bug** in the previously existing codebase (`BackEndApp`).

### Possible Solution

Create a new `Django Bug.md` file in `.github/ISSUE_TEMPLATE` directory.

### Additional Context

Remember to add comments in the template so as to guide the user appropriately (when the template is used).

**Comment by ankit-kmar** [comment]
please assign me this issue.

**Comment by camperjett** [comment]
Hi @McTechie. If @ankit-kmar is not interested in this, can I take up this issue. I Would love to contribute

**Comment by McTechie** [comment]
@ankit-kmar it would be great if you could give us a status update of your work

**Comment by ADI10HERO** [comment]
Closing this Issue as per discussion on slack. Thanks to all contributors. Requesting y'all to have a look at other open issues. 😄
