### ISSUE TITLE
Dynamic component for Payment integration

### ISSUE THREAD

**Issue by rajraj889** [Auto-DL/Auto-DL#377]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

See #375 

### Feature Description

Make the component dynamic if no prop is passed, it should take the amount from user, otherwise make the payment for the passed prop (amount)

### Additional context

While pushing the code, remove all the API keys and replace it with API_KEY or according names.

**Comment by priyanshm07** [comment]
Hello @rajraj889,
Does this feature fall under #375 Assigned to me?

**Comment by rajraj889** [comment]
Yes we need a dynamic component where if a value is passed then it should accept that payment  otherwise user can make payment for any amount.

**Comment by priyanshm07** [comment]
Great then,
@rajraj889 could you please assign this one to me.
