### ISSUE TITLE
run.sh fails

### ISSUE THREAD

**Issue by Rahul524** [Auto-DL/Auto-DL#383]
## Bug Report

Space in folder name gives error.
### Current Behavior

Script fails
Error: ./scripts/run.sh: line 84: cd: too many arguments

### Expected behavior/code
run.sh should work

### ⚙️ Environment

- `OS`: Ubuntu 18.04

**Comment by niyoj** [comment]
Can I work on this issue?

**Comment by BRO3886** [comment]
If it hasn't been assigned I'd be happy to take it up

**Comment by McTechie** [comment]
@niyoj yes you can definitely work on this and create a PR to fix it.
If you're up for it I'd assign this issue to you :D

**Comment by McTechie** [comment]
@BRO3886 meanwhile you could browse for other ones. In case this one isn't fixed, you could take it up later! xD

**Comment by McTechie** [comment]
@BRO3886 @kyteinsky would either of you be willing to take this one up?

**Comment by BRO3886** [comment]
Sure, I'd love to try
Expected time: 1 day

**Comment by McTechie** [comment]
Sure, go ahead with it then! xD

**Comment by niyoj** [comment]
@McTechie Sorry I was offline due to network issues in my locality. I was finding the way to solve this issue.

**Comment by BRO3886** [comment]
Can you give me 12 hours more, if I'm unable to come up with a solution please assign it back to @niyoj

**Comment by niyoj** [comment]
@BRO3886 Since you are assigned and you are working on this issue from my side take your time. Till then I will be looking on other issues.
