### ISSUE TITLE
User Profile page in Django

### ISSUE THREAD

**Issue by rajraj889** [Auto-DL/Auto-DL#385]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

New implementation

### Feature Description

Profile section needed for user, where he/she can edit some details and add a profile pic

### Possible Solution

Create backend routes for required frontend actions, check #384

**Comment by rohith1125** [comment]
@rajraj889 I think I can do this, please assign this to me

**Comment by McTechie** [comment]
Heyy @rohith1125, I've assigned this to you now. If you do feel stuck or need help, feel free to reach out! :D

**Comment by McTechie** [comment]
Heyy @techonerd I've assigned this to you. If you have any doubts or face any blockers do feel free to reach out here or via Slack!
