### ISSUE TITLE
Update sample.env for backend

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Auto-DL#393]
### Current Behavior
Backend sample.env is not updated

### Expected behavior/code
Sample to have env vars for all cases

### ⚙️ Environment

- `Python` version(s): All
- `OS`: All

### Possible Solution

Have sample.env look something like this:
```
# required
MONGO_URI=......
....
...
# deployment 
FLASK_URI=....
...
..
# upload to github
GITHUB_ID=...
....
...
```

### Additional context/Screenshots
Ppl will know the bare minimum needed to run the application and can add stuff as they want them :D

**Comment by ADI10HERO** [comment]
PS: Not a hacktoberfest issue and needs experience with Auto-DL to take this up :)

**Comment by McTechie** [comment]
@ADI10HERO I'll take this up! 😄
