### ISSUE TITLE
Correct typos in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sokratis12GR** [Auto-DL/Auto-DL#396]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

As the title suggests, there are some typos throughout the CONTRIBUTING.md file that need to be corrected.

### Possible Solution

Yes, making this issue to correlate with a pull request I'm preparing. #397 

### Additional context

Some typos can cause confusion to new contributors.

**Comment by askalik** [comment]
Could I be assigned this ?
