### ISSUE TITLE
I'm trying to run the project but when i'm running "sudo ./scripts/run.sh it shows ./scripts/run.sh: line 84: cd: too many arguments How do i fix it? OS - ubuntu 20.04

### ISSUE THREAD

**Issue by sparsh9** [Auto-DL/Auto-DL#403]
### ⚙️ Environment

- `Python` version(s):
    - *good*: [e.g. 3.8]
    - **better**: [3.8.6 - Clang 12.0.0 (clang-1200.0.32.27)]
- `OS`: [e.g. Ubuntu 18.04, OSX 10.13.4, Windows 10]

**Comment by McTechie** [comment]
Hey, @sparsh9 an Issue for this has already been created (#383).

**Comment by sparsh9** [comment]
Okay.
