### ISSUE TITLE
run.sh new frontend support 

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Auto-DL#452]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

Parameter to build/run the frontend of choice
-f or --frontend with options: v1 and v2 (default)

on v1: same routine as now
v2: starts autodl-platform nextjs application

**Comment by ashish-ad** [comment]
Hey @ADI10HERO, I would like to work on this as I have proposed in my proposal for WOC and I need help in locating both the version please provide some help

**Comment by ADI10HERO** [comment]
Hey @ashish-ad  Sure...

@rajraj889 Can you please help him?

**Comment by ashish-ad** [comment]
Hey @rajraj889, I am facing an issue in locating the files that will contain both versions. 
Need Ur guidance.
