### ISSUE TITLE
Bump up adaptV4Theme deprecation in V2 frontend

### ISSUE THREAD

**Issue by McTechie** [Auto-DL/Auto-DL#457]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

The `adaptV4Theme()` appears to be deprecated in `FrontEndApp/autodl-platform` (V2 codebase in NextJS).

![image](https://user-images.githubusercontent.com/69250084/142749780-9b4cc423-8fcb-4dc8-8178-b6bc722321c2.png)

### Possible Solution

Finding an acclaimed alternative to replace `adaptV4Theme()`.

P.s. It should be compatible with our NextJS (TS) + Material UI (v5) codebase.

**Comment by ShwetKhatri2001** [comment]
I'd like to make it compatible
