### ISSUE TITLE
FrontEndApp path inaccurate in "npm install" step

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [Auto-DL/Auto-DL#484]
### Current Behaviour

- Go to https://docs.auto-dl.tech/en/latest/installing.html
- Scroll down to https://docs.auto-dl.tech/en/latest/installing.html#installing-the-requirements-and-running-the-app under Windows section
- On below mentioned step, there is no package.json, hence we cannot use `npm install` to install the dependencies. Package.json is present inside FrontEndApp/v1-react. 
```
 cd Auto-DL/FrontEndApp
 npm install
```

### Expected Behaviour

Package.json is present inside FrontEndApp/v1-react.  So we need to update the path accordingly.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ADI10HERO** [comment]
Hey @ShreyaPrasad1209
We need to add "/autodl_platform" and "/v1-react" depending on the version of FrontEnd:
* v1-react --> Old react application ()
* autodl-platform --> New nextjs application (preferred)

**Comment by ShreyaPrasad1209** [comment]
> Hey @ShreyaPrasad1209 We need to add "/autodl_platform" and "/v1-react" depending on the version of FrontEnd:
> 
> * v1-react --> Old react application (not actively developed)
> * autodl-platform --> New nextjs application (preferred)

Okay can I mention this in the docs? Otherwise it is confusing as to inside which folder we need to start the server.

**Comment by ADI10HERO** [comment]
yes please :)

**Comment by ShreyaPrasad1209** [comment]
> yes please :)

I've made the changes. Can you please look through the linked PR?
