### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by adityaraute** [Auto-DL/Auto-DL#92]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation? **NO**

### Feature Description

A linter will ensure that the quality of code is homogeneous throughout all contributions. Later on, we can also add a GitHub Action to verify whether the code has been linted appropriately or not.

### Possible Solution

I will try to work with setting up 'ESlint' for the project. And thus the command `npm lint` or `npm run lint` can be used for the project.

**Comment by RusherRG** [comment]
I'm assigning this issue to myself. Already added linter for python in #213 and would add similar pre-commit hooks and workflows for ESLint.

**Comment by ADI10HERO** [comment]
Updating milestone to V2

**Comment by McTechie** [comment]
@RusherRG can we close this one? [Since ESLint is added in #300]

**Comment by RusherRG** [comment]
Yeah let's close
