### ISSUE TITLE
Linting Errors

### ISSUE THREAD

**Issue by adityaraute** [Auto-DL/Auto-DL#97]
## Bug Report

When I tried to set up `eslint` on save, for the repository, these are the issues that were encountered. A lot of those can be, and will be, converted to warnings. However, I felt it was important to list all the linting errors so that the contributors can take care of it and thus the linter can be merged in the project.

### Current Behavior

After running `npm start`, a stream of linting errors is generated that should be taken care of. I am attaching the pdf file here.
[AUTO DL SCREENCAPTURE.pdf](https://github.com/Auto-DL/Generator/files/5881033/AUTO.DL.SCREENCAPTURE.pdf)

### Expected behavior/code

Those practices as listed should be taken care of, and the respective errors be cleared at the earliest. 

### Additional context/Screenshots

Here's the list of all possible [rules](https://eslint.org/docs/rules/) for `eslint`

**Comment by adityaraute** [comment]
Anyone working on this?

**Comment by rajraj889** [comment]
Not as of now, will do this after the project is kind of complete, I just need 2-3 days more

**Comment by adityaraute** [comment]
Want me to assist you in this? I'll get some basic stuff done at least.

**Comment by ADI10HERO** [comment]
> Want me to assist you in this? I'll get some basic stuff done at least.

Sure @adityaraute

**Comment by adityaraute** [comment]
Now I forgot everything about it. 😂

**Comment by ADI10HERO** [comment]
> Now I forgot everything about it. 😂

I understand 🤣 Well any help is appreciated. :)

**Comment by McTechie** [comment]
Fixed in #300 (V2 created in NextJS)
